### ISSUE TITLE
web pages are not responsive and inconsistent throughout different browsers

### ISSUE THREAD

**Issue by atulchavan10000** [atulchavan10000/projectdebug#6]
- May need to apply bootstrap for making it responsive,
- Need to investigate for consistent appearance with all major browsers and all sizes of monitors and all   kind of devices.

**Comment by Amir-Khan06** [comment]
By using Bootstrap framework the issue will be resolved, Bootstrap not only helps the website to be responsive but also ensures that the webpages are loading same in different browsers and screen size.It manages our web components as per the convenience.
Secondly, but as we know we have to test everything what we make, so we will indulge in cross-browser testing. Its very easy and takes only a few minutes of task.

I hereby conclude that we all must learn Bootstrap framework as soon as possible.
